const QUIZ_DATA = {
  kemerdekaan: {
    label: 'Kemerdekaan Indonesia',
    icon: '🇮🇩',
    questions: [
      { q: 'Pada tanggal berapa Indonesia memproklamasikan kemerdekaannya?', options: ['17 Agustus 1945', '20 Mei 1945', '28 Oktober 1928', '1 Juni 1945'], answer: 0 },
      { q: 'Siapa yang membacakan teks Proklamasi Kemerdekaan Indonesia?', options: ['Mohammad Hatta', 'Ir. Soekarno', 'Soeharto', 'Sutan Sjahrir'], answer: 1 },
      { q: 'Siapa yang menjahit Bendera Pusaka Sang Saka Merah Putih?', options: ['Cut Nyak Dhien', 'R.A. Kartini', 'Fatmawati', 'Dewi Sartika'], answer: 2 },
      { q: 'Di jalan apa teks Proklamasi dibacakan di Jakarta?', options: ['Jl. Sudirman', 'Jl. Pegangsaan Timur No. 56', 'Jl. Thamrin', 'Jl. Gajah Mada'], answer: 1 },
      { q: 'Siapa pencipta lagu "Indonesia Raya"?', options: ['Ismail Marzuki', 'W.R. Supratman', 'Gesang', 'C. Simanjuntak'], answer: 1 },
      { q: 'Siapa Wakil Presiden pertama Republik Indonesia?', options: ['Sutan Sjahrir', 'Mohammad Hatta', 'Ahmad Soebardjo', 'Radjiman Wedyodiningrat'], answer: 1 },
      { q: 'Pada perayaan tahun 2026, HUT Kemerdekaan RI diperingati yang ke berapa?', options: ['ke-79', 'ke-80', 'ke-81', 'ke-82'], answer: 2 },
      { q: 'Apa semboyan negara Indonesia yang tertera pada lambang Garuda Pancasila?', options: ['Bhinneka Tunggal Ika', 'Merdeka atau Mati', 'Tut Wuri Handayani', 'Jer Basuki Mawa Beya'], answer: 0 },
      { q: 'Dokumen yang menjadi dasar berdirinya Republik Indonesia setelah proklamasi disebut?', options: ['Piagam Jakarta', 'UUD 1945', 'Sumpah Pemuda', 'Dekrit Presiden'], answer: 1 },
      { q: 'Peristiwa penting sebelum proklamasi di mana para pemuda mendesak Soekarno-Hatta segera memproklamasikan kemerdekaan disebut?', options: ['Peristiwa Rengasdengklok', 'Peristiwa Madiun', 'Serangan Umum 1 Maret', 'Pertempuran Surabaya'], answer: 0 },
    ],
  },
  vtuber: {
    label: 'VTuber Indonesia',
    icon: '🎌',
    questions: [
      { q: 'VTuber adalah singkatan dari?', options: ['Video Tuber', 'Virtual YouTuber', 'Visual Tuber', 'Vector Tuber'], answer: 1 },
      { q: 'Di Virtara Project, sebutan untuk penggemar/fans adalah?', options: ['Oshi', 'Vira', 'Fansu', 'Kouhai'], answer: 1 },
      { q: 'Apa nama tema Generation 1 Virtara Project?', options: ['Dreams of Bali', 'Echoes of Sumatra', 'Voices of Java', 'Winds of Papua'], answer: 1 },
      { q: 'Apa nama tema Generation 2 Virtara Project?', options: ['Echoes of Sumatra', 'Dreams of Bali', 'Legends of Kalimantan', 'Spirit of Sulawesi'], answer: 1 },
      { q: 'Talent Virtara dengan julukan "Sang Ratu Lautan" bernama?', options: ['Talitha Hikari', 'Adinda Chelia', 'Odelia Chandana', 'Lumi Avelline'], answer: 1 },
      { q: 'Berapa jumlah talent di Generation 2 Virtara Project?', options: ['3', '6', '9', '2'], answer: 1 },
      { q: 'Model karakter VTuber pada umumnya digerakkan menggunakan teknologi?', options: ['Motion capture / Live2D', 'CGI film studio', 'Stop motion', 'Rotoscope manual'], answer: 0 },
      { q: 'Istilah "debut" dalam dunia VTuber merujuk pada?', options: ['Pensiunnya seorang talent', 'Kemunculan publik pertama seorang talent', 'Kolaborasi dua talent', 'Ulang tahun agensi'], answer: 1 },
      { q: 'Talitha Hikari digambarkan sebagai karakter bertema apa?', options: ['Arwah dari langit', 'Ratu lautan', 'Ngengat', 'Prajurit galaksi'], answer: 0 },
      { q: 'Siaran langsung seorang VTuber ke penontonnya secara umum disebut?', options: ['Livestream', 'Podcast', 'Webinar', 'Broadcast studio'], answer: 0 },
    ],
  },
  umum: {
    label: 'Pengetahuan Umum',
    icon: '🌎',
    questions: [
      { q: 'Planet terbesar di tata surya adalah?', options: ['Mars', 'Jupiter', 'Saturnus', 'Neptunus'], answer: 1 },
      { q: 'Berapa jumlah sisi pada bangun segitiga?', options: ['2', '3', '4', '5'], answer: 1 },
      { q: 'Apa ibu kota Jepang?', options: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], answer: 2 },
      { q: 'Hewan yang dijuluki "Raja Hutan" adalah?', options: ['Harimau', 'Singa', 'Gajah', 'Serigala'], answer: 1 },
      { q: 'Berapa jumlah hari pada tahun kabisat?', options: ['364', '365', '366', '367'], answer: 2 },
      { q: 'Gas apa yang paling banyak terkandung di atmosfer Bumi?', options: ['Oksigen', 'Karbon Dioksida', 'Nitrogen', 'Hidrogen'], answer: 2 },
      { q: 'Siapa tokoh yang dikenal luas sebagai penemu bola lampu?', options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'James Watt'], answer: 1 },
      { q: 'Apa nama mata uang resmi Jepang?', options: ['Won', 'Yen', 'Yuan', 'Ringgit'], answer: 1 },
      { q: 'Apa ibu kota Perancis?', options: ['London', 'Roma', 'Paris', 'Madrid'], answer: 2 },
      { q: 'Berapa jumlah kaki yang dimiliki laba-laba?', options: ['6', '8', '10', '4'], answer: 1 },
    ],
  },
};